openapi: 3.0.2
info:
  title: Housing Price Prediction API
  version: 1.0.0
  description: |
    API provides real-time house price predictions for properties in the Seattle area.
servers:
  - url: https://api.soundrealty.ai/v1
    description: Production server
  - url: http://localhost:8000
    description: Local development server

paths:
  /predict:
    post:
      summary: Predict the house price
      description: >
        Takes in property features such as number of bedrooms, bathrooms,
        living area square footage, and zipcode, and returns the model’s predicted price.
      operationId: predictHousePrice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HouseFeatures'
            example:
              bedrooms: 3
              bathrooms: 2
              sqft_living: 1800
              sqft_lot: 4000
              floors: 1.5
              waterfront: 0
              view: 1
              condition: 3
              grade: 7
              sqft_above: 1500
              sqft_basement: 300
              yr_built: 1985
              yr_renovated: 0
              zipcode: "98103"
      responses:
        '200':
          description: Successful prediction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PredictionResponse'
              example:
                predicted_price: 724500.50
                model_version: "1"

components:
  schemas:
    HouseFeatures:
      type: object
      properties:
        bedrooms:
          type: integer
          example: 3
        bathrooms:
          type: number
          example: 2
        sqft_living:
          type: integer
          example: 1800
        sqft_lot:
          type: integer
          example: 4000
        floors:
          type: number
          example: 1.5
        waterfront:
          type: integer
          enum: [0, 1]
          example: 0
        view:
          type: integer
          example: 1
        condition:
          type: integer
          example: 3
        grade:
          type: integer
          example: 7
        sqft_above:
          type: integer
          example: 1500
        sqft_basement:
          type: integer
          example: 300
        yr_built:
          type: integer
          example: 1985
        yr_renovated:
          type: integer
          example: 0
        zipcode:
          type: string
          example: "98103"
      required:
        - bedrooms
        - bathrooms
        - sqft_living
        - zipcode

    PredictionResponse:
      type: object
      properties:
        predicted_price:
          type: number
          format: float
          example: 724500.50
        model_version:
          type: string
          example: "1"
